/* Profilfoto: lokaler Zuschnitt im Basisprofil, steuerbar je Variante. */
(() => {
  const css = `
  .profile-photo-box{display:flex;align-items:center;gap:16px;flex-wrap:wrap}.base-photo{width:82px;height:82px;border:1px solid var(--line);border-radius:50%;object-fit:cover;background:#e6ecf5}.photo-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.photo-note{font-size:12px;color:var(--muted);line-height:1.45;max-width:560px}.variant-photo-toggle{padding-top:4px}.preview-person{display:flex;align-items:center;justify-content:space-between;gap:14px}.preview-person-copy{min-width:0}.preview-photo{width:72px;height:72px;object-fit:cover;border-radius:50%;border:2px solid rgba(255,255,255,.72);background:#e6ecf5;flex:0 0 auto}.photo-crop-dialog{width:min(760px,100%)}.photo-crop-stage{position:relative;width:min(540px,100%);aspect-ratio:1;margin:16px auto;background:#162b43;overflow:hidden;touch-action:none;cursor:grab}.photo-crop-stage.dragging{cursor:grabbing}.photo-crop-stage img{position:absolute;max-width:none;user-select:none;pointer-events:none}.photo-crop-frame{position:absolute;inset:0;border:2px solid #fff;box-shadow:0 0 0 200vmax rgba(20,61,106,.43);pointer-events:none}.photo-crop-controls{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.photo-crop-controls input{width:min(300px,100%)}.photo-crop-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}
  `;
  document.head.insertAdjacentHTML('beforeend', `<style>${css}</style>`);
  let sourceImage=null, crop={scale:1,x:0,y:0,min:1}, dragging=null;
  const imageUrl=()=>profile?.person?.foto?.url||'';
  const initials=()=>((profile?.person?.vorname||'')[0]||'')+((profile?.person?.nachname||'')[0]||'');
  const photoMarkup=(className='base-photo')=>imageUrl()?`<img class="${className}" src="${e(imageUrl())}?v=${encodeURIComponent(profile?.person?.foto?.aktualisiertAm||'')}" alt="Profilfoto">`:`<div class="avatar" style="width:82px;height:82px;font-size:20px">${e(initials().toUpperCase()||'–')}</div>`;
  const originalRenderBase=window.renderBase;
  window.renderBase=function(){
    originalRenderBase();
    const head=q('#base > .row'); if(!head||q('#profile-photo-section'))return;
    const section=document.createElement('section'); section.className='section'; section.id='profile-photo-section';
    section.innerHTML=`<h3>Profilfoto</h3><div class="profile-photo-box"><div id="base-photo-current">${photoMarkup()}</div><div><div class="photo-actions"><label class="button secondary" for="profile-photo-input">Foto auswählen</label><input id="profile-photo-input" type="file" accept="image/jpeg,image/png" hidden>${imageUrl()?'<button class="remove" type="button" onclick="removeProfilePhoto()">Foto entfernen</button>':''}</div><p class="photo-note">JPG und PNG. Du legst den quadratischen Ausschnitt selbst fest; gespeichert wird ein kompaktes JPG mit maximal 640 × 640 Pixel.</p></div></div>`;
    head.insertAdjacentElement('afterend',section); q('#profile-photo-input').addEventListener('change',event=>openCrop(event.target));
  };
  function cropDialog(){
    let modal=q('#photo-crop-modal'); if(modal)return modal;
    modal=document.createElement('div'); modal.id='photo-crop-modal'; modal.className='modal';
    modal.innerHTML=`<div class="dialog photo-crop-dialog" role="dialog" aria-modal="true" aria-labelledby="photo-crop-title"><div class="row"><div><h2 id="photo-crop-title">Foto zuschneiden</h2><p class="intro">Ziehe das Bild in den Ausschnitt und wähle den Bildausschnitt mit dem Zoom.</p></div></div><div id="photo-crop-stage" class="photo-crop-stage"><img id="photo-crop-image" alt="Auswahl für das Profilfoto"><div class="photo-crop-frame"></div></div><div class="photo-crop-controls"><label for="photo-crop-zoom">Zoom</label><input id="photo-crop-zoom" type="range" min="1" max="3" step="0.01" value="1"></div><div class="photo-crop-actions"><button type="button" class="button secondary" onclick="cancelPhotoCrop()">Abbrechen</button><button type="button" class="button" onclick="savePhotoCrop()">Ausschnitt übernehmen</button></div></div>`;
    document.body.append(modal); const stage=q('#photo-crop-stage'); stage.addEventListener('pointerdown',startDrag); window.addEventListener('pointermove',moveDrag); window.addEventListener('pointerup',stopDrag); q('#photo-crop-zoom').addEventListener('input',event=>{crop.scale=Number(event.target.value); clampCrop(); paintCrop();}); return modal;
  }
  window.openCrop=function(input){
    const file=input.files?.[0]; input.value=''; if(!file)return;
    if(!['image/jpeg','image/png'].includes(file.type)){say('Bitte ein JPG- oder PNG-Bild auswählen.');return;}
    if(file.size>12*1024*1024){say('Das Ausgangsbild ist zu groß. Bitte eine Datei unter 12 MB auswählen.');return;}
    const reader=new FileReader(); reader.onerror=()=>say('Die Bilddatei konnte nicht gelesen werden.'); reader.onload=()=>{sourceImage=new Image(); sourceImage.onerror=()=>say('Die Bilddatei ist nicht lesbar.'); sourceImage.onload=()=>{const stage=cropDialog(); stage.classList.add('open'); const size=q('#photo-crop-stage').clientWidth; crop.min=Math.max(size/sourceImage.naturalWidth,size/sourceImage.naturalHeight); crop.scale=1; crop.x=(size-sourceImage.naturalWidth*crop.min)/2; crop.y=(size-sourceImage.naturalHeight*crop.min)/2; q('#photo-crop-zoom').value='1'; paintCrop();}; sourceImage.src=reader.result;}; reader.readAsDataURL(file);
  };
  function paintCrop(){if(!sourceImage)return;const stage=q('#photo-crop-stage'),img=q('#photo-crop-image'),size=stage.clientWidth,scale=crop.min*crop.scale; img.style.width=`${sourceImage.naturalWidth*scale}px`;img.style.height=`${sourceImage.naturalHeight*scale}px`;img.style.left=`${crop.x}px`;img.style.top=`${crop.y}px`;}
  function clampCrop(){const size=q('#photo-crop-stage').clientWidth,scale=crop.min*crop.scale,w=sourceImage.naturalWidth*scale,h=sourceImage.naturalHeight*scale;crop.x=Math.min(0,Math.max(size-w,crop.x));crop.y=Math.min(0,Math.max(size-h,crop.y));}
  function startDrag(event){if(!sourceImage)return;dragging={x:event.clientX,y:event.clientY,photoX:crop.x,photoY:crop.y};q('#photo-crop-stage').classList.add('dragging');event.currentTarget.setPointerCapture?.(event.pointerId);}
  function moveDrag(event){if(!dragging)return;crop.x=dragging.photoX+event.clientX-dragging.x;crop.y=dragging.photoY+event.clientY-dragging.y;clampCrop();paintCrop();}
  function stopDrag(){dragging=null;q('#photo-crop-stage')?.classList.remove('dragging');}
  window.cancelPhotoCrop=function(){q('#photo-crop-modal')?.classList.remove('open');sourceImage=null;};
  window.savePhotoCrop=async function(){if(!sourceImage)return;const stage=q('#photo-crop-stage'),size=stage.clientWidth,canvas=document.createElement('canvas');canvas.width=640;canvas.height=640;const ctx=canvas.getContext('2d'),scale=crop.min*crop.scale;ctx.drawImage(sourceImage,crop.x/scale,crop.y/scale,size/scale,size/scale,0,0,640,640);let dataUrl=canvas.toDataURL('image/jpeg',.86);if(dataUrl.length>1_100_000)dataUrl=canvas.toDataURL('image/jpeg',.72);try{profile=await api('/profiles/'+profile.id+'/photo','POST',{dataUrl});cancelPhotoCrop();render();if(variant)showPreview();say('Profilfoto gespeichert.');}catch(error){say(error.message||'Das Profilfoto konnte nicht gespeichert werden.');}};
  window.removeProfilePhoto=async function(){if(!confirm('Profilfoto entfernen? Es wird aus dem Basisprofil und allen Varianten-Ausgaben entfernt.'))return;try{profile=await api('/profiles/'+profile.id+'/photo','DELETE');render();if(variant)showPreview();say('Profilfoto entfernt.');}catch(error){say(error.message||'Das Profilfoto konnte nicht entfernt werden.');}};
  const originalVariants=window.variants;
  window.variants=async function(edit=false){await originalVariants(edit);if(!edit||!variant)return;const context=q('.variant-editor .section');if(!context||context.querySelector('.variant-photo-toggle'))return;const fields=context.querySelector('.fields');if(!fields)return;const row=document.createElement('div');row.className='field wide variant-photo-toggle';row.innerHTML=imageUrl()?`<label class="check"><input type="checkbox" ${variant.fotoSichtbar?'checked':''} onchange="photoVisibilityChanged(this)"> Profilfoto in dieser Variante anzeigen</label><div class="photo-note">Die Auswahl gilt auch für den PDF-Export.</div>`:`<div class="photo-note">Für dieses Profil ist noch kein Foto hinterlegt. Fotos pflegst du im Basisprofil.</div>`;fields.append(row);};
  window.photoVisibilityChanged=function(box){variant.fotoSichtbar=box.checked;variantChanged();showPreview();};
  const originalShowPreview=window.showPreview;
  window.showPreview=function(){originalShowPreview();if(!variant?.fotoSichtbar||!imageUrl())return;const person=q('#variant-preview .preview-person');if(!person||person.querySelector('.preview-photo'))return;const copy=document.createElement('div');copy.className='preview-person-copy';while(person.firstChild)copy.append(person.firstChild);person.append(copy);person.insertAdjacentHTML('beforeend',photoMarkup('preview-photo'));};
  const originalSaveVariant=window.saveVariant;
  window.saveVariant=async function(freigeben){const previous=variant?.fotoSichtbar;const result=await originalSaveVariant(freigeben);if(variant&&previous!==undefined)variant.fotoSichtbar=previous;return result;};
})();
